service: monitoring

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10
  memorySize: ${self:custom.memorySize}
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${self:custom.region}
  profile: potech-serverless

  iamRoleStatements:
  - Effect: Allow
    Action:
      - sqs:SendMessage
      - sqs:DeleteMessage
      - sqs:ReceiveMessage
      - sqs:GetQueueAttributes
    Resource:
      - Fn::GetAtt: [ JobQueue, Arn ]
  - Effect: Allow
    Action:
      - secretsmanager:GetSecretValue
    Resource: '*'

custom: 
  region: us-east-1
  memorySize: 128
  defaultStage: local
  profiles:
    dev: potech-serverless
    local: potech-serverless
    prod: potech-serverless
  googleSheetId: ${opt:sheetId}
  googleSecretKeyId: ${self:service}-${self:provider.stage}-key

  localstack:
    stages:
      - local
    host: http://localhost
    autostart: true
    endpoints:
      DynamoDB: http://localhost:4569
      CloudFormation: http://localhost:4581
      SQS: http://localhost:4576
    lambda:
      mountCode: True
    docker:
      sudo: False

plugins:
  - serverless-localstack
  - serverless-mocha-plugin

package:
  excludeDevDependencies: true
  exclude:
    - .keys/**

functions:
  publish:
    reservedConcurrency: 3
    handler: src/publisher/publish.handler
    environment:
      QUEUE_URL:
        Ref: JobQueue
    events:
      - http:
          path: publish
          method: post
          cors: true

  consumer:
    reservedConcurrency: 1
    handler: src/consumer/consume.handler
    environment:
      GOOGLE_SA_EMAIL: ${file(.keys/gsheetKey.json):client_email}
      GOOGLE_PK_SECRET_ID: ${self:custom.googleSecretKeyId}
      GOOGLE_SHEET_ID: ${self:custom.googleSheetId}
    events:
      - sqs:
          batchSize: 10
          arn:
            Fn::GetAtt: [ JobQueue, Arn ]

  # dlqConsumer:
    # reservedConcurrency: 1
    # handler: src/consumer/consume.handler
    # environment:
      # GOOGLE_SA_EMAIL: ${file(.keys/gsheetKey.json):client_email}
      # GOOGLE_PK_SECRET_ID: ${self:custom.googleSecretKeyId}
      # GOOGLE_SHEET_ID: ${self:custom.googleSheetId}
    # events:
      # - sqs:
          # batchSize: 10
          # arn:
            # Fn::GetAtt: [ DeadLetterQueue, Arn ]

resources:
  - ${file(resources/googleKey.yml)}
  - ${file(resources/jobsQueue.yml)}
  - ${file(resources/apiKey.yml)}
